# Generated by Django 4.2.4 on 2023-10-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_loadwallet_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet',
            new_name='account_balance',
        ),
    ]
